import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:marketim/api/Autogenerated.dart';
import 'package:http/http.dart' as http;

class apiCall {
  Future<Autogenerated>? getcurrentapi() async {
    var endpoint = Uri.parse("https://fakestoreapi.com/products/1");
    var response = await http.get(endpoint);
    var body = jsonDecode(response.body);
    print(Autogenerated.fromJson(body).title);
    return Autogenerated.fromJson(body);
  }
}

class apiurun extends StatefulWidget {
  const apiurun({Key? key}) : super(key: key);

  @override
  State<apiurun> createState() => _apiurunState();
}

class _apiurunState extends State<apiurun> {
  apiCall auto = apiCall();
  Autogenerated? data;

  Future<void> getData() async {
    data = await auto.getcurrentapi();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: FutureBuilder(
            future: getData(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.done) {
                return Scaffold(
                  appBar: AppBar(
                    backgroundColor: Colors.redAccent,
                  ),
                  body: SafeArea(
                    child: Center(
                      child: ListView(
                        children: [
                          const SizedBox(height: 30),
                          Image.network("${data?.image}"),
                          const SizedBox(height: 30),
                          Text("${data?.title}"),
                          const SizedBox(height: 10),
                          Text("${data?.price} TL"),
                          const SizedBox(height: 32),
                          SizedBox(
                            width: 300,
                            height: 80,
                            child: ElevatedButton(
                                style: ButtonStyle(
                                    backgroundColor:
                                        MaterialStateProperty.all(Colors.blue)),
                                onPressed: () {
                                  showDialog(
                                      context: context,
                                      builder: (context) => AlertDialog(
                                            title: const Text("Tamam"),
                                            content:
                                                const Text("Sepete Eklendi!"),
                                            actions: [
                                              TextButton(
                                                  onPressed: () {
                                                    Navigator.pop(context);
                                                  },
                                                  child: const Text("Kapat"))
                                            ],
                                          ));
                                },
                                child: const Text("Sepete Ekle")),
                          ),
                          const SizedBox(height: 20)
                        ],
                      ),
                    ),
                  ),
                );
              } else if (snapshot.connectionState == ConnectionState.waiting) {
                return const Center(
                  child: CircularProgressIndicator(),
                );
              }
              return Container();
            }));
  }
}
